version: '3'
services:
    app:
        image: voicenotes:latest
        container_name: voicenotes_app
        ports:
            - 80:80
        volumes:
            - ./:/var/www/
        working_dir: /var/www/
        links:
            - db
        build:
            context: .
            dockerfile: .docker/php/Dockerfile.dev
        environment:
          - REVAI_ACCESS_TOKEN
          - CALLBACK_PREFIX
          - MONGODB_URI
        entrypoint: ["/var/www/.docker/php/entrypoint.sh"]
        command: ["apache2-foreground"]
    db:
        image: mongo:latest
        container_name: voicenotes_db
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: myuser
          MONGO_INITDB_ROOT_PASSWORD: mypassword
        volumes:
            - data:/data/db/
        ports:
            - 27017:27017
volumes:
    data: {}