version: '3'
services:
    app:
        image: myapp
        ports:
            - 80:80
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./.docker/apache/myapp.conf:/etc/apache2/sites-enabled/000-default.conf
        links:
            - db
        build:
            context: .
            dockerfile: .docker/php/Dockerfile.dev
    db:
        image: mongo:latest
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: myuser
          MONGO_INITDB_ROOT_PASSWORD: mypassword
          MONGO_INITDB_DATABASE: mydb
        volumes:
            - data:/data/db/
        ports:
            - 27017:27017
volumes:
    data: {}