FROM php:7.4-apache
RUN apt-get update \
  && apt-get install -y libcurl4-openssl-dev pkg-config libssl-dev zlib1g-dev zip git \
  && pecl install mongodb \
  && docker-php-ext-enable mongodb
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN a2enmod rewrite
EXPOSE 80